# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='math.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nmath.proto\"\x1c\n\x0bSqrtRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"\x1d\n\x0cSqrtResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32-\n\x04Math\x12%\n\x04Sqrt\x12\x0c.SqrtRequest\x1a\r.SqrtResponse\"\x00\x62\x06proto3')
)




_SQRTREQUEST = _descriptor.Descriptor(
  name='SqrtRequest',
  full_name='SqrtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SqrtRequest.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=42,
)


_SQRTRESPONSE = _descriptor.Descriptor(
  name='SqrtResponse',
  full_name='SqrtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='SqrtResponse.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['SqrtRequest'] = _SQRTREQUEST
DESCRIPTOR.message_types_by_name['SqrtResponse'] = _SQRTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SqrtRequest = _reflection.GeneratedProtocolMessageType('SqrtRequest', (_message.Message,), dict(
  DESCRIPTOR = _SQRTREQUEST,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:SqrtRequest)
  ))
_sym_db.RegisterMessage(SqrtRequest)

SqrtResponse = _reflection.GeneratedProtocolMessageType('SqrtResponse', (_message.Message,), dict(
  DESCRIPTOR = _SQRTRESPONSE,
  __module__ = 'math_pb2'
  # @@protoc_insertion_point(class_scope:SqrtResponse)
  ))
_sym_db.RegisterMessage(SqrtResponse)



_MATH = _descriptor.ServiceDescriptor(
  name='Math',
  full_name='Math',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=75,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sqrt',
    full_name='Math.Sqrt',
    index=0,
    containing_service=None,
    input_type=_SQRTREQUEST,
    output_type=_SQRTRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATH)

DESCRIPTOR.services_by_name['Math'] = _MATH

# @@protoc_insertion_point(module_scope)
